# Generated by Django 5.1.6 on 2026-02-24 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('material_type', models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], max_length=10)),
                ('dirty_bags_used', models.PositiveIntegerField()),
                ('approx_dirty_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('clean_bags_produced', models.PositiveIntegerField()),
                ('loss_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cleaning_batches', to='accounts.user')),
                ('cleaning_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cleaning_batches', to='accounts.user')),
                ('raw_issuance', models.ForeignKey(blank=True, help_text='Issuance record this cleaning batch draws from', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cleaning_batches', to='procurement.rawmaterialissuance')),
            ],
            options={
                'db_table': 'cleaning_batch',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CleanRawReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('material_type', models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], max_length=10)),
                ('num_bags', models.PositiveIntegerField()),
                ('weight_per_bag_kg', models.PositiveIntegerField(default=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('cleaning_batch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='store_receipt', to='cleaning.cleaningbatch')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clean_receipts', to='accounts.user')),
            ],
            options={
                'db_table': 'cleaning_clean_receipt',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
