# Generated by Django 4.2.27 on 2026-02-24 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_active_user_status'),
        ('cleaning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningbatch',
            name='cleaning_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cleaning_batches', to='accounts.user'),
        ),
    ]
