# Generated by Django 6.0.2 on 2026-03-12 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0002_alter_cleaningbatch_cleaning_manager'),
        ('procurement', '0004_rawmaterialreceipt_cost_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleanrawreceipt',
            name='cleaning_batch',
        ),
        migrations.AddField(
            model_name='cleanrawreceipt',
            name='approx_dirty_weight_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cleanrawreceipt',
            name='loss_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cleanrawreceipt',
            name='raw_issuance',
            field=models.ForeignKey(blank=True, help_text='Issuance record this receipt draws from', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clean_receipts', to='procurement.rawmaterialissuance'),
        ),
        migrations.DeleteModel(
            name='CleaningBatch',
        ),
    ]
