# Generated by Django 5.1.6 on 2026-02-24 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedGoodsIssuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_size', models.CharField(choices=[('1kg', '1 KG'), ('5kg', '5 KG'), ('10kg', '10 KG')], max_length=5)),
                ('qty_issued', models.PositiveIntegerField()),
                ('channel', models.CharField(choices=[('company', 'Company Direct'), ('promoter', 'Sales Promoter'), ('driver', 'Vehicle Driver')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fg_issued_by', to='accounts.user')),
                ('issued_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fg_issued_to', to='accounts.user')),
            ],
            options={
                'db_table': 'finished_store_issuance',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinishedGoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_size', models.CharField(choices=[('1kg', '1 KG'), ('5kg', '5 KG'), ('10kg', '10 KG')], max_length=5)),
                ('qty_received', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('production_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished_receipts', to='production.productionbatch')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fg_receipts', to='accounts.user')),
            ],
            options={
                'db_table': 'finished_store_receipt',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
