# Generated by Django 4.2.27 on 2026-02-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finished_store', '0002_alter_finishedgoodsissuance_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedgoodsissuance',
            name='product_size',
            field=models.CharField(choices=[('1kg', '1 KG'), ('10kg', '10 KG')], max_length=5),
        ),
        migrations.AlterField(
            model_name='finishedgoodsreceipt',
            name='product_size',
            field=models.CharField(choices=[('1kg', '1 KG'), ('10kg', '10 KG')], max_length=5),
        ),
    ]
