# Generated by Django 4.2.27 on 2026-02-26 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finished_store', '0003_alter_finishedgoodsissuance_product_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishedgoodsreceipt',
            name='production_batch',
        ),
    ]
