# Generated by Django 4.2.27 on 2026-02-26 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_millingbatch_packagingbatch_delete_productionbatch'),
        ('finished_store', '0004_remove_finishedgoodsreceipt_production_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgoodsreceipt',
            name='packaging_batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='finished_receipts', to='production.packagingbatch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finishedgoodsissuance',
            name='product_size',
            field=models.CharField(choices=[('10kg', '10 KG')], max_length=5),
        ),
        migrations.AlterField(
            model_name='finishedgoodsreceipt',
            name='product_size',
            field=models.CharField(choices=[('10kg', '10 KG')], max_length=5),
        ),
    ]
