# Generated by Django 4.2.27 on 2026-02-26 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
        ('finished_store', '0005_finishedgoodsreceipt_packaging_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgoodsissuance',
            name='rejection_note',
            field=models.TextField(blank=True, help_text='Reason for rejection'),
        ),
        migrations.AddField(
            model_name='finishedgoodsissuance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
        migrations.CreateModel(
            name='FinishedGoodsReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_size', models.CharField(choices=[('10kg', '10 KG')], max_length=5)),
                ('qty_returned', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('rejection_note', models.TextField(blank=True, help_text='Reason for rejection')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fg_return_received', to='accounts.user')),
                ('returned_by', models.ForeignKey(limit_choices_to={'role': 'sales_user'}, on_delete=django.db.models.deletion.PROTECT, related_name='fg_returned_by', to='accounts.user')),
            ],
            options={
                'db_table': 'finished_store_return',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
