# Generated by Django 4.2.27 on 2026-02-27 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_phase1_roles_and_salesperson'),
        ('sales', '0008_phase2_pricing_and_fg_store'),
        ('finished_store', '0006_finishedgoodsissuance_rejection_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgoodsissuance',
            name='material_type',
            field=models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], default='maize', max_length=10),
        ),
        migrations.AddField(
            model_name='finishedgoodsissuance',
            name='sales_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issuances', to='sales.salesrecord'),
        ),
        migrations.AddField(
            model_name='finishedgoodsreceipt',
            name='material_type',
            field=models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], default='maize', max_length=10),
        ),
        migrations.AddField(
            model_name='finishedgoodsreturn',
            name='material_type',
            field=models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], default='maize', max_length=10),
        ),
        migrations.AlterField(
            model_name='finishedgoodsissuance',
            name='product_size',
            field=models.CharField(choices=[('10kg', '10 KG'), ('5kg', '5 KG'), ('1kg', '1 KG')], max_length=5),
        ),
        migrations.AlterField(
            model_name='finishedgoodsreceipt',
            name='product_size',
            field=models.CharField(choices=[('10kg', '10 KG'), ('5kg', '5 KG'), ('1kg', '1 KG')], max_length=5),
        ),
        migrations.AlterField(
            model_name='finishedgoodsreturn',
            name='product_size',
            field=models.CharField(choices=[('10kg', '10 KG'), ('5kg', '5 KG'), ('1kg', '1 KG')], max_length=5),
        ),
        migrations.AlterField(
            model_name='finishedgoodsreturn',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fg_return_received', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='finishedgoodsreturn',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fg_returned_by', to='accounts.user'),
        ),
    ]
