# Generated by Django 4.2.27 on 2026-02-28 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_sales_user_type_alter_user_role'),
        ('finished_store', '0007_phase2_pricing_and_fg_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishedgoodsreceipt',
            name='packaging_batch',
        ),
        migrations.AddField(
            model_name='finishedgoodsreceipt',
            name='packaging_ref',
            field=models.CharField(blank=True, help_text='Display ref e.g. "Packaging Batch #7"', max_length=50),
        ),
        migrations.AddField(
            model_name='finishedgoodsreceipt',
            name='rejection_note',
            field=models.TextField(blank=True, help_text='Reason for rejection'),
        ),
        migrations.AddField(
            model_name='finishedgoodsreceipt',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='finishedgoodsreceipt',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fg_receipts_submitted', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='finishedgoodsreceipt',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fg_receipts_acknowledged', to='accounts.user'),
        ),
    ]
