# Generated by Django 4.2.27 on 2026-03-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finished_store', '0008_receipt_ledger_handshake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedgoodsissuance',
            name='product_size',
            field=models.CharField(choices=[('10kg', '10 KG')], max_length=5),
        ),
        migrations.AlterField(
            model_name='finishedgoodsreceipt',
            name='product_size',
            field=models.CharField(choices=[('10kg', '10 KG')], max_length=5),
        ),
        migrations.AlterField(
            model_name='finishedgoodsreturn',
            name='product_size',
            field=models.CharField(choices=[('10kg', '10 KG')], max_length=5),
        ),
    ]
