# Generated by Django 5.1.6 on 2026-03-01 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finished_store', '0009_alter_finishedgoodsissuance_product_size_and_more'),
        ('sales', '0012_alter_salesrecord_channel_salesmanagercollection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgoodsissuance',
            name='sm_collection',
            field=models.ForeignKey(blank=True, help_text='The SM collection this issuance was recorded against', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issuances', to='sales.salesmanagercollection'),
        ),
        migrations.AlterField(
            model_name='finishedgoodsissuance',
            name='channel',
            field=models.CharField(choices=[('company', 'Company Direct'), ('sales_manager', 'Sales Manager'), ('promoter', 'Sales Promoter (Legacy)'), ('driver', 'Vehicle Driver (Legacy)')], max_length=15),
        ),
    ]
