# Generated by Django 6.0.2 on 2026-03-09 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_plain_password'),
        ('finished_store', '0010_finishedgoodsissuance_sm_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgoodsissuance',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='GM or MD designated to confirm this company issuance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fg_issuances_to_approve', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='finishedgoodsissuance',
            name='buyer_name',
            field=models.CharField(blank=True, help_text='Name of the customer or entity receiving the goods (company sales)', max_length=200),
        ),
    ]
