# Generated by Django 6.0.2 on 2026-04-05 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finished_store', '0011_finishedgoodsissuance_approver_and_more'),
        ('production', '0008_remove_packagingbatch_is_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgoodsreceipt',
            name='packaging_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fg_receipts', to='production.packagingbatch'),
        ),
    ]
