# Generated by Django 5.1.6 on 2026-02-24 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('company', 'Company Direct'), ('promoter', 'Sales Promoter'), ('driver', 'Vehicle Driver')], max_length=10)),
                ('product_size', models.CharField(choices=[('1kg', '1 KG'), ('5kg', '5 KG'), ('10kg', '10 KG')], max_length=5)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'md'}, on_delete=django.db.models.deletion.PROTECT, to='accounts.user')),
            ],
            options={
                'db_table': 'pricing_config',
                'ordering': ['-effective_from', 'channel', 'product_size'],
            },
        ),
    ]
