# Generated by Django 4.2.27 on 2026-02-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_alter_priceconfig_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceconfig',
            name='product_size',
            field=models.CharField(choices=[('10kg', '10 KG')], max_length=5),
        ),
    ]
