# Generated by Django 4.2.27 on 2026-02-27 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_phase1_roles_and_salesperson'),
        ('pricing', '0004_alter_priceconfig_product_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceconfig',
            options={'ordering': ['-effective_from', 'channel', 'material_type', 'product_size']},
        ),
        migrations.AddField(
            model_name='priceconfig',
            name='material_type',
            field=models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], default='maize', help_text='Maize or Wheat', max_length=10),
        ),
        migrations.AlterField(
            model_name='priceconfig',
            name='product_size',
            field=models.CharField(choices=[('10kg', '10 KG'), ('5kg', '5 KG'), ('1kg', '1 KG')], max_length=5),
        ),
        migrations.CreateModel(
            name='CommissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('promoter', 'Sales Promoter'), ('driver', 'Vehicle Driver')], help_text='Commission applies to promoter or driver channel', max_length=10)),
                ('material_type', models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], default='maize', max_length=10)),
                ('product_size', models.CharField(choices=[('10kg', '10 KG'), ('5kg', '5 KG'), ('1kg', '1 KG')], max_length=5)),
                ('commission_pct', models.DecimalField(decimal_places=2, help_text='Commission percentage (e.g. 10.00 = 10%)', max_digits=5)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'md'}, on_delete=django.db.models.deletion.PROTECT, to='accounts.user')),
            ],
            options={
                'db_table': 'pricing_commission_config',
                'ordering': ['-effective_from', 'channel', 'material_type', 'product_size'],
            },
        ),
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], default='maize', max_length=10)),
                ('product_size', models.CharField(choices=[('10kg', '10 KG'), ('5kg', '5 KG'), ('1kg', '1 KG')], max_length=5)),
                ('month', models.PositiveSmallIntegerField(help_text='Month number 1–12')),
                ('year', models.PositiveSmallIntegerField()),
                ('target_qty', models.PositiveIntegerField(help_text='Target number of sacks to sell')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'md'}, on_delete=django.db.models.deletion.PROTECT, related_name='targets_set', to='accounts.user')),
                ('sales_manager', models.ForeignKey(limit_choices_to={'role': 'sales_manager'}, on_delete=django.db.models.deletion.PROTECT, related_name='sales_targets', to='accounts.user')),
            ],
            options={
                'db_table': 'pricing_sales_target',
                'ordering': ['-year', '-month', 'sales_manager__full_name'],
                'unique_together': {('sales_manager', 'material_type', 'product_size', 'month', 'year')},
            },
        ),
    ]
