# Generated by Django 4.2.27 on 2026-03-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_phase2_pricing_and_fg_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionconfig',
            name='product_size',
            field=models.CharField(choices=[('10kg', '10 KG')], max_length=5),
        ),
        migrations.AlterField(
            model_name='priceconfig',
            name='product_size',
            field=models.CharField(choices=[('10kg', '10 KG')], max_length=5),
        ),
        migrations.AlterField(
            model_name='salestarget',
            name='product_size',
            field=models.CharField(choices=[('10kg', '10 KG')], max_length=5),
        ),
    ]
