# Generated by Django 5.1.6 on 2026-03-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_alter_commissionconfig_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceconfig',
            name='channel',
            field=models.CharField(choices=[('company', 'Company Direct'), ('sales_manager', 'Sales Manager'), ('promoter', 'Sales Promoter (Legacy)'), ('driver', 'Vehicle Driver (Legacy)')], max_length=15),
        ),
    ]
