# Generated by Django 6.0 on 2026-03-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_alter_priceconfig_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionconfig',
            name='channel',
            field=models.CharField(choices=[('sales_team', 'Sales Team')], help_text='Commission applies to everyone in the sales team', max_length=20),
        ),
    ]
