# Generated by Django 6.0.2 on 2026-03-09 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_plain_password'),
        ('pricing', '0008_alter_commissionconfig_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(help_text='E.g., Fuel, Salaries, Maintenance', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(limit_choices_to={'role': 'md'}, on_delete=django.db.models.deletion.PROTECT, to='accounts.user')),
            ],
            options={
                'db_table': 'pricing_expense',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackagingCostConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], default='maize', max_length=10)),
                ('cost_per_sack', models.DecimalField(decimal_places=2, help_text='Cost of one empty sack + stitching/branding', max_digits=10)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'md'}, on_delete=django.db.models.deletion.PROTECT, to='accounts.user')),
            ],
            options={
                'db_table': 'pricing_packaging_cost',
                'ordering': ['-effective_from', 'material_type'],
            },
        ),
    ]
