# Generated by Django 6.0.2 on 2026-03-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_plain_password'),
        ('pricing', '0009_operationalexpense_packagingcostconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salestarget',
            options={'ordering': ['-year', '-month', '-week', 'sales_manager__full_name']},
        ),

        migrations.AddField(
            model_name='salestarget',
            name='target_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='salestarget',
            name='week',
            field=models.PositiveSmallIntegerField(blank=True, help_text='ISO week number 1–53', null=True),
        ),
        migrations.AlterField(
            model_name='salestarget',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Month number 1–12', null=True),
        ),
        migrations.AlterField(
            model_name='salestarget',
            name='product_size',
            field=models.CharField(choices=[('10kg', '10 KG')], default='10kg', max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='salestarget',
            unique_together={('sales_manager', 'material_type', 'product_size', 'target_type', 'month', 'week', 'year')},
        ),
    ]
