# Generated by Django 6.0.2 on 2026-04-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_alter_salestarget_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingcostconfig',
            name='cleaning_cost_per_bag',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pre-cleaning payment per 100kg raw bag', max_digits=10),
        ),
        migrations.AddField(
            model_name='packagingcostconfig',
            name='nylon_cost_per_piece',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost of one nylon liner', max_digits=10),
        ),
    ]
