# Generated by Django 6.0.2 on 2026-04-07 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_plain_password'),
        ('pricing', '0011_packagingcostconfig_cleaning_cost_per_bag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagingcostconfig',
            options={'ordering': ['-effective_from']},
        ),
        migrations.RemoveField(
            model_name='packagingcostconfig',
            name='cleaning_cost_per_bag',
        ),
        migrations.RemoveField(
            model_name='packagingcostconfig',
            name='material_type',
        ),
        migrations.CreateModel(
            name='CleaningCostConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], default='maize', max_length=10)),
                ('cleaning_cost_per_bag', models.DecimalField(decimal_places=2, default=0, help_text='Pre-cleaning payment per 100kg raw bag', max_digits=10)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'md'}, on_delete=django.db.models.deletion.PROTECT, to='accounts.user')),
            ],
            options={
                'db_table': 'pricing_cleaning_cost',
                'ordering': ['-effective_from', 'material_type'],
            },
        ),
    ]
