# Generated by Django 6.0.2 on 2026-04-11 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_plain_password'),
        ('pricing', '0012_alter_packagingcostconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourCostConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_cleaning_cost_per_bag', models.DecimalField(decimal_places=2, default=0, help_text='Labor cost paid per clean bag produced', max_digits=10)),
                ('general_labour_cost_per_sack', models.DecimalField(decimal_places=2, default=0, help_text='General labor cost paid per confirmed sold 10kg sack', max_digits=10)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'md'}, on_delete=django.db.models.deletion.PROTECT, to='accounts.user')),
            ],
            options={
                'db_table': 'pricing_labour_cost',
                'ordering': ['-effective_from'],
            },
        ),
    ]
