# Generated by Django 6.0.2 on 2026-04-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0013_labourcostconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labourcostconfig',
            name='general_labour_cost_per_sack',
        ),
        migrations.RemoveField(
            model_name='labourcostconfig',
            name='pre_cleaning_cost_per_bag',
        ),
        migrations.AddField(
            model_name='labourcostconfig',
            name='labour_cost_per_sack',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Labour cost per 10kg sack sold (automated)', max_digits=10),
        ),
    ]
