# Generated by Django 6.0.2 on 2026-04-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0014_remove_labourcostconfig_general_labour_cost_per_sack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourcostconfig',
            name='labour_cost_per_sack',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Labour cost per 100kg raw bag milled (automated)', max_digits=10),
        ),
    ]
