# Generated by Django 5.1.6 on 2026-02-24 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clean_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=10)),
                ('material_type', models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], max_length=10)),
                ('machine', models.CharField(blank=True, max_length=100)),
                ('bags_collected', models.PositiveIntegerField(help_text='Number of clean 100kg bags collected from store')),
                ('bags_processed', models.PositiveIntegerField(default=0, help_text='Bags actually milled in this batch')),
                ('bags_outstanding', models.PositiveIntegerField(default=0, help_text='Auto: bags_collected - bags_processed')),
                ('qty_1kg', models.PositiveIntegerField(default=0)),
                ('qty_5kg', models.PositiveIntegerField(default=0)),
                ('qty_10kg', models.PositiveIntegerField(default=0)),
                ('total_output_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_raw_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loss_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loss_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('flag_level', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('flag_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('complete', 'Complete'), ('flagged', 'Flagged')], default='open', max_length=10)),
                ('is_locked', models.BooleanField(default=True)),
                ('correction_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clean_raw_issuance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='clean_store.cleanrawissuance')),
                ('production_officer', models.ForeignKey(limit_choices_to={'role': 'production_officer'}, on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='accounts.user')),
                ('unlocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_batches', to='accounts.user')),
            ],
            options={
                'db_table': 'production_batch',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], max_length=10)),
                ('standard_weight_per_bag_kg', models.PositiveIntegerField(default=100)),
                ('expected_loss_pct', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('normal_max_loss_pct', models.DecimalField(decimal_places=2, default=13.0, max_digits=5)),
                ('warning_max_loss_pct', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'md'}, on_delete=django.db.models.deletion.PROTECT, to='accounts.user')),
            ],
            options={
                'db_table': 'production_threshold',
                'ordering': ['-effective_from'],
            },
        ),
    ]
