# Generated by Django 4.2.27 on 2026-02-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionbatch',
            name='qty_1kg',
        ),
        migrations.RemoveField(
            model_name='productionbatch',
            name='qty_5kg',
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='qty_10kg',
            field=models.PositiveIntegerField(default=0, help_text='Number of 10kg sacks packaged'),
        ),
    ]
