# Generated by Django 4.2.27 on 2026-02-26 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finished_store', '0004_remove_finishedgoodsreceipt_production_batch'),
        ('accounts', '0003_alter_user_role'),
        ('clean_store', '0001_initial'),
        ('production', '0002_remove_productionbatch_qty_1kg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MillingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=10)),
                ('material_type', models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], max_length=10)),
                ('machine', models.CharField(blank=True, max_length=100)),
                ('bags_collected', models.PositiveIntegerField(help_text='Number of clean 100kg bags collected from store')),
                ('bags_milled', models.PositiveIntegerField(default=0, help_text='Bags actually milled in this batch')),
                ('bags_outstanding', models.PositiveIntegerField(default=0, help_text='Auto: bags_collected - bags_milled')),
                ('bulk_powder_kg', models.DecimalField(decimal_places=2, help_text='Actual weight of powder produced', max_digits=12)),
                ('total_raw_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loss_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loss_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('flag_level', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('flag_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('complete', 'Complete'), ('flagged', 'Flagged')], default='open', max_length=10)),
                ('is_locked', models.BooleanField(default=True)),
                ('correction_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('clean_raw_issuance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='milling_batches', to='clean_store.cleanrawissuance')),
                ('production_officer', models.ForeignKey(limit_choices_to={'role': 'production_officer'}, on_delete=django.db.models.deletion.PROTECT, related_name='milling_batches', to='accounts.user')),
                ('unlocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_milling_batches', to='accounts.user')),
            ],
            options={
                'db_table': 'production_milling_batch',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackagingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=10)),
                ('material_type', models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], max_length=10)),
                ('powder_used_kg', models.DecimalField(decimal_places=2, help_text='Kg of powder used', max_digits=12)),
                ('qty_10kg', models.PositiveIntegerField(default=0, help_text='Number of 10kg sacks packaged')),
                ('total_output_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loss_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loss_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_locked', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('milling_batch', models.ForeignKey(help_text='Milling batch this powder is drawn from', on_delete=django.db.models.deletion.PROTECT, related_name='packaging_batches', to='production.millingbatch')),
                ('production_officer', models.ForeignKey(limit_choices_to={'role': 'production_officer'}, on_delete=django.db.models.deletion.PROTECT, related_name='packaging_batches', to='accounts.user')),
            ],
            options={
                'db_table': 'production_packaging_batch',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ProductionBatch',
        ),
    ]
