# Generated by Django 4.2.27 on 2026-02-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_millingbatch_packagingbatch_delete_productionbatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='millingbatch',
            name='bags_collected',
        ),
        migrations.RemoveField(
            model_name='millingbatch',
            name='bags_milled',
        ),
        migrations.RemoveField(
            model_name='millingbatch',
            name='bags_outstanding',
        ),
        migrations.RemoveField(
            model_name='millingbatch',
            name='clean_raw_issuance',
        ),
        migrations.AddField(
            model_name='millingbatch',
            name='bags_milled_new',
            field=models.PositiveIntegerField(default=0, help_text='New bags milled today (from Available Balance)'),
        ),
        migrations.AddField(
            model_name='millingbatch',
            name='outstanding_bags_milled',
            field=models.PositiveIntegerField(default=0, help_text='Old bags milled today (from Outstanding)'),
        ),
    ]
