# Generated by Django 4.2.27 on 2026-02-27 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_phase1_roles_and_salesperson'),
        ('production', '0004_remove_millingbatch_bags_collected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('material_type', models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], max_length=10)),
                ('qty_sacks', models.PositiveIntegerField(help_text='Number of brand sacks sold')),
                ('buyer_name', models.CharField(max_length=200)),
                ('price_per_sack', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('mixed', 'Cash + Transfer')], max_length=10)),
                ('amount_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_transfer', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('recorded_by', models.ForeignKey(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.PROTECT, related_name='brand_sales', to='accounts.user')),
            ],
            options={
                'db_table': 'production_brand_sale',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
