# Generated by Django 4.2.27 on 2026-03-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_phase5_brand_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingbatch',
            name='flag_level',
            field=models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('critical', 'Critical')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='packagingbatch',
            name='flag_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productionthreshold',
            name='expected_loss_pct',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productionthreshold',
            name='normal_max_loss_pct',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productionthreshold',
            name='warning_max_loss_pct',
            field=models.DecimalField(decimal_places=2, default=19.0, max_digits=5),
        ),
    ]
