# Generated by Django 6.0.2 on 2026-04-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_packagingbatch_flag_level_packagingbatch_flag_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingbatch',
            name='is_issued',
            field=models.BooleanField(default=False),
        ),
    ]
