# Generated by Django 6.0.2 on 2026-04-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_remove_packagingbatch_is_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingbatch',
            name='packaging_unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='packagingbatch',
            name='total_packaging_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
