# Generated by Django 6.0.2 on 2026-04-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_populate_packaging_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='millingbatch',
            name='labour_unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='millingbatch',
            name='total_labour_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
