# Generated by Django 5.1.6 on 2026-02-24 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('store_officer', 'Store Officer'), ('cleaning_manager', 'Cleaning Manager'), ('production_officer', 'Production Officer'), ('sales_user', 'Sales User'), ('sales_manager', 'Sales Manager'), ('manager', 'Manager'), ('md', 'Managing Director')], max_length=30)),
                ('sales_user_type', models.CharField(blank=True, choices=[('promoter', 'Sales Promoter'), ('driver', 'Vehicle Driver'), ('company', 'Company Direct')], help_text='Only for sales_user role', max_length=20, null=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
            options={
                'db_table': 'accounts_user',
                'ordering': ['full_name'],
            },
        ),
    ]
