# Generated by Django 4.2.27 on 2026-02-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_active_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('store_officer', 'Store Officer'), ('production_officer', 'Production Officer'), ('sales_user', 'Sales User'), ('sales_manager', 'Sales Manager'), ('manager', 'Manager'), ('md', 'Managing Director')], max_length=30),
        ),
    ]
