# Generated by Django 4.2.27 on 2026-02-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='user',
            name='store_type',
            field=models.CharField(blank=True, choices=[('raw', 'Raw Material Store'), ('finished', 'Finished Goods Store')], help_text='Only for store_officer role: raw or finished goods store', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('store_officer', 'Store Officer'), ('production_officer', 'Production Officer'), ('sales_user', 'Sales User'), ('sales_manager', 'Sales Manager'), ('manager', 'General Manager'), ('md', 'Managing Director')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='sales_user_type',
            field=models.CharField(blank=True, choices=[('promoter', 'Sales Promoter'), ('driver', 'Vehicle Driver'), ('company', 'Company Direct')], help_text='Only for sales_user role (promoter/driver — cannot log in; company = can log in)', max_length=20, null=True),
        ),
    ]
