# Generated by Django 4.2.27 on 2026-02-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_phase1_roles_and_salesperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sales_user_type',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('store_officer', 'Store Officer'), ('production_officer', 'Production Officer'), ('sales_manager', 'Sales Manager'), ('manager', 'General Manager'), ('md', 'Managing Director')], max_length=30),
        ),
    ]
