# Generated by Django 4.2.27 on 2026-03-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_sales_user_type_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sales_user_type',
            field=models.CharField(blank=True, choices=[('promoter', 'Sales Promoter'), ('driver', 'Company Driver')], help_text='Only for sales_user role: promoter or driver', max_length=10, null=True),
        ),
    ]
