# Generated by Django 6.0.2 on 2026-03-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_sales_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, help_text='Visible password for administrative reference', max_length=128, null=True),
        ),
    ]
