# Generated by Django 5.1.6 on 2026-02-24 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('transfer_received', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('from_user', models.ForeignKey(limit_choices_to={'role': 'sales_user'}, on_delete=django.db.models.deletion.PROTECT, related_name='money_paid', to='accounts.user')),
                ('linked_sales_records', models.ManyToManyField(blank=True, related_name='money_receipts', to='sales.salesrecord')),
                ('sales_manager', models.ForeignKey(limit_choices_to={'role': 'sales_manager'}, on_delete=django.db.models.deletion.PROTECT, related_name='money_receipts', to='accounts.user')),
            ],
            options={
                'db_table': 'reconciliation_money_receipt',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flagged_by', models.ForeignKey(limit_choices_to={'role': 'sales_manager'}, on_delete=django.db.models.deletion.PROTECT, related_name='created_flags', to='accounts.user')),
                ('sales_user', models.ForeignKey(limit_choices_to={'role': 'sales_user'}, on_delete=django.db.models.deletion.PROTECT, related_name='recon_flags', to='accounts.user')),
            ],
            options={
                'db_table': 'reconciliation_flag',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
