# Generated by Django 4.2.27 on 2026-02-26 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('settlement_type', models.CharField(choices=[('return', 'Return to Store'), ('payment', 'Cash Payment'), ('loss', 'Approved Loss')], max_length=10)),
                ('source_type', models.CharField(choices=[('production_batch', 'Production Batch'), ('sales_custody', 'Sales Custody')], max_length=20)),
                ('source_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_settlements_approved', to='accounts.user')),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_settlements_received', to='accounts.user')),
            ],
            options={
                'db_table': 'reconciliation_stock_settlement',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
