# Generated by Django 4.2.27 on 2026-02-26 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0002_stocksettlement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockSettlement',
        ),
    ]
