# Generated by Django 4.2.27 on 2026-02-28 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_phase2_pricing_and_fg_store'),
        ('reconciliation', '0003_delete_stocksettlement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneyreceipt',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='reconciliationflag',
            name='sales_user',
        ),
        migrations.AddField(
            model_name='moneyreceipt',
            name='sales_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='money_paid', to='sales.salesperson'),
        ),
        migrations.AddField(
            model_name='reconciliationflag',
            name='sales_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recon_flags', to='sales.salesperson'),
        ),
    ]
