# Generated by Django 6.0.2 on 2026-04-05 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_user_plain_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('clean_maize_bags', models.IntegerField(default=0)),
                ('clean_wheat_bags', models.IntegerField(default=0)),
                ('dirty_maize_bags', models.IntegerField(default=0)),
                ('dirty_wheat_bags', models.IntegerField(default=0)),
                ('prod_maize_hand', models.IntegerField(default=0)),
                ('prod_wheat_hand', models.IntegerField(default=0)),
                ('prod_maize_transit', models.IntegerField(default=0)),
                ('prod_wheat_transit', models.IntegerField(default=0)),
                ('prod_maize_milled_bags', models.IntegerField(default=0)),
                ('prod_wheat_milled_bags', models.IntegerField(default=0)),
                ('prod_maize_packaged_sacks', models.IntegerField(default=0)),
                ('prod_wheat_packaged_sacks', models.IntegerField(default=0)),
                ('fg_maize_10kg', models.IntegerField(default=0)),
                ('fg_wheat_10kg', models.IntegerField(default=0)),
                ('sm_maize_holding', models.IntegerField(default=0)),
                ('sm_wheat_holding', models.IntegerField(default=0)),
                ('sm_money_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gm_maize_hand', models.IntegerField(default=0)),
                ('gm_wheat_hand', models.IntegerField(default=0)),
                ('gm_retail_pieces_maize', models.IntegerField(default=0)),
                ('gm_retail_pieces_wheat', models.IntegerField(default=0)),
                ('gm_direct_sale_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.user')),
            ],
            options={
                'db_table': 'reports_monthly_snapshot',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
