# Generated by Django 5.1.6 on 2026-02-24 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanRawIssuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('material_type', models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], max_length=10)),
                ('num_bags', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clean_raw_issued_by', to='accounts.user')),
                ('issued_to', models.ForeignKey(limit_choices_to={'role': 'production_officer'}, on_delete=django.db.models.deletion.PROTECT, related_name='clean_raw_issued_to', to='accounts.user')),
            ],
            options={
                'db_table': 'clean_store_issuance',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CleanRawReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('material_type', models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], max_length=10)),
                ('num_bags', models.PositiveIntegerField()),
                ('production_batch_ref', models.CharField(blank=True, help_text='Production batch ID reference', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clean_raw_return_received', to='accounts.user')),
                ('returned_by', models.ForeignKey(limit_choices_to={'role': 'production_officer'}, on_delete=django.db.models.deletion.PROTECT, related_name='clean_raw_returned_by', to='accounts.user')),
            ],
            options={
                'db_table': 'clean_store_return',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
