# Generated by Django 4.2.27 on 2026-02-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleanrawreturn',
            name='production_batch_ref',
        ),
        migrations.AddField(
            model_name='cleanrawissuance',
            name='rejection_note',
            field=models.TextField(blank=True, help_text='Reason for rejection'),
        ),
        migrations.AddField(
            model_name='cleanrawissuance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='cleanrawreturn',
            name='rejection_note',
            field=models.TextField(blank=True, help_text='Reason for rejection'),
        ),
        migrations.AddField(
            model_name='cleanrawreturn',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
    ]
