# Generated by Django 4.2.27 on 2026-02-28 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_sales_user_type_alter_user_role'),
        ('clean_store', '0002_remove_cleanrawreturn_production_batch_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanrawreturn',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clean_raw_return_received', to='accounts.user'),
        ),
    ]
