# Generated by Django 5.1.6 on 2026-02-24 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('material_type', models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], max_length=10)),
                ('supplier', models.CharField(max_length=200)),
                ('num_bags', models.PositiveIntegerField()),
                ('approx_weight_kg', models.DecimalField(decimal_places=2, help_text='Approximate total weight in kg', max_digits=10)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_receipts', to='accounts.user')),
            ],
            options={
                'db_table': 'procurement_receipt',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterialIssuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('material_type', models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], max_length=10)),
                ('num_bags_issued', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_issued_by', to='accounts.user')),
                ('issued_to', models.ForeignKey(limit_choices_to={'role': 'cleaning_manager'}, on_delete=django.db.models.deletion.PROTECT, related_name='raw_issued_to', to='accounts.user')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuances', to='procurement.rawmaterialreceipt')),
            ],
            options={
                'db_table': 'procurement_issuance',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
