# Generated by Django 4.2.27 on 2026-02-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialissuance',
            name='issued_to',
            field=models.CharField(help_text='Name of the cleaner or contractor', max_length=200),
        ),
    ]
