# Generated by Django 4.2.27 on 2026-03-01 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_alter_rawmaterialissuance_issued_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialissuance',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issuances', to='procurement.rawmaterialreceipt'),
        ),
    ]
