# Generated by Django 6.0.2 on 2026-03-09 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_plain_password'),
        ('procurement', '0003_alter_rawmaterialissuance_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialreceipt',
            name='cost_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterialreceipt',
            name='cost_approved_by',
            field=models.ForeignKey(blank=True, help_text='MD who set the cost for this receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_costs_approved', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='rawmaterialreceipt',
            name='cost_per_bag',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Purchase cost per bag (entered by MD)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterialreceipt',
            name='cost_status',
            field=models.CharField(choices=[('pending', 'Pending MD Review'), ('approved', 'Cost Approved')], default='pending', help_text='Whether the MD has reviewed and set the cost for this receipt', max_length=10),
        ),
        migrations.AddField(
            model_name='rawmaterialreceipt',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total purchase cost = cost_per_bag × num_bags (auto-calculated)', max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='CleaningLossConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], max_length=10)),
                ('max_loss_pct', models.DecimalField(decimal_places=2, help_text='Maximum acceptable cleaning loss percentage (e.g. 5.00 = 5%)', max_digits=5)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'md'}, on_delete=django.db.models.deletion.PROTECT, related_name='cleaning_loss_configs', to='accounts.user')),
            ],
            options={
                'db_table': 'procurement_cleaning_loss_config',
                'ordering': ['-effective_from', 'material_type'],
            },
        ),
    ]
