# Generated by Django 6.0.2 on 2026-04-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_rawmaterialreceipt_cost_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialissuance',
            name='is_fully_received',
            field=models.BooleanField(default=False, help_text='Set to True when all clean bags are back in store'),
        ),
    ]
