# Generated by Django 6.0.2 on 2026-04-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_rawmaterialissuance_is_fully_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialissuance',
            name='cleaning_unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawmaterialissuance',
            name='total_cleaning_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
