# Generated by Django 5.1.6 on 2026-02-24 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('finished_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCustody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_size', models.CharField(choices=[('1kg', '1 KG'), ('5kg', '5 KG'), ('10kg', '10 KG')], max_length=5)),
                ('qty_collected', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fg_issuance', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='custody', to='finished_store.finishedgoodsissuance')),
                ('sales_user', models.ForeignKey(limit_choices_to={'role': 'sales_user'}, on_delete=django.db.models.deletion.PROTECT, related_name='custody_records', to='accounts.user')),
            ],
            options={
                'db_table': 'sales_custody',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_size', models.CharField(choices=[('1kg', '1 KG'), ('5kg', '5 KG'), ('10kg', '10 KG')], max_length=5)),
                ('channel', models.CharField(choices=[('company', 'Company Direct'), ('promoter', 'Sales Promoter'), ('driver', 'Vehicle Driver')], max_length=10)),
                ('qty_sold', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('custody', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_records', to='sales.salescustody')),
                ('sales_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_records', to='accounts.user')),
            ],
            options={
                'db_table': 'sales_record',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
