# Generated by Django 4.2.27 on 2026-02-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_salescustody_product_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrecord',
            name='custody',
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='qty_sold_new',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='qty_sold_outstanding',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='qty_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SalesCustody',
        ),
    ]
