# Generated by Django 4.2.27 on 2026-02-26 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
        ('sales', '0005_remove_salesrecord_custody_salesrecord_qty_sold_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'sales_manager'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acknowledged_sales', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='amount_received_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='amount_received_transfer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='manager_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Manager Acknowledgment'), ('acknowledged', 'Acknowledged')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('mixed', 'Cash + Transfer')], max_length=10),
        ),
    ]
