# Generated by Django 4.2.27 on 2026-02-27 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_phase1_roles_and_salesperson'),
        ('sales', '0006_salesrecord_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrecord',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='qty_sold_new',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='qty_sold_outstanding',
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='commission_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='material_type',
            field=models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], default='maize', help_text='Maize or Wheat', max_length=10),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='net_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'sales_manager'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_sales', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='sales_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_records', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Issuance'), ('issued', 'Goods Issued'), ('paid', 'Fully Paid'), ('partial', 'Partially Paid')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('promoter', 'Sales Promoter'), ('driver', 'Vehicle Driver')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(default='active', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salesperson_created', to='accounts.user')),
            ],
            options={
                'db_table': 'sales_person',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_transfer', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payments', to='accounts.user')),
                ('sales_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.salesrecord')),
            ],
            options={
                'db_table': 'sales_payment',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_records', to='sales.salesperson'),
        ),
    ]
