# Generated by Django 4.2.27 on 2026-02-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_phase1_roles_and_salesperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='product_size',
            field=models.CharField(choices=[('10kg', '10 KG'), ('5kg', '5 KG'), ('1kg', '1 KG')], max_length=5),
        ),
    ]
