# Generated by Django 4.2.27 on 2026-02-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_phase2_pricing_and_fg_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrecord',
            name='sales_user',
        ),
    ]
