# Generated by Django 4.2.27 on 2026-03-01 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_sales_user_type_alter_user_role'),
        ('sales', '0009_remove_salesrecord_sales_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='product_size',
            field=models.CharField(choices=[('10kg', '10 KG Sacks'), ('1kg', '1 KG Pieces (Retail)')], default='10kg', max_length=10),
        ),
        migrations.CreateModel(
            name='CompanyRetailLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('material_type', models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], default='maize', max_length=10)),
                ('action', models.CharField(choices=[('open_sack', 'Opened 10kg Sack (+10 pieces)'), ('retail_sale', 'Retail Sale (Deduction)'), ('adjustment', 'Manager Adjustment')], max_length=20)),
                ('pieces_changed', models.IntegerField(help_text='Positive for added pieces, negative for sold pieces')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retail_ledger_actions', to='accounts.user')),
                ('sales_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_deductions', to='sales.salesrecord')),
            ],
            options={
                'db_table': 'sales_retail_ledger',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
