# Generated by Django 4.2.27 on 2026-03-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_salesrecord_product_size_companyretailledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='buyer_name',
            field=models.CharField(blank=True, help_text='For direct company retail sales where no sales person is involved.', max_length=200),
        ),
    ]
