# Generated by Django 5.1.6 on 2026-03-01 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_sales_user_type_alter_user_role'),
        ('sales', '0011_salesrecord_buyer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='channel',
            field=models.CharField(choices=[('company', 'Company Direct'), ('sales_manager', 'Sales Manager'), ('promoter', 'Sales Promoter (Legacy)'), ('driver', 'Vehicle Driver (Legacy)')], max_length=15),
        ),
        migrations.CreateModel(
            name='SalesManagerCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date goods were physically handed over')),
                ('material_type', models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], max_length=10)),
                ('qty_sacks', models.PositiveIntegerField(help_text='Number of 10kg sacks collected')),
                ('price_per_sack', models.DecimalField(decimal_places=2, default=0, help_text='Price per 10kg sack at the time of collection (from MD price config)', max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, help_text='Total expected value = price_per_sack × qty_sacks', max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending Acknowledgement'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_note', models.TextField(blank=True, help_text='Reason if SM rejected collection')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('sales_manager', models.ForeignKey(limit_choices_to={'role': 'sales_manager'}, on_delete=django.db.models.deletion.PROTECT, related_name='sm_collections', to='accounts.user')),
                ('store_officer', models.ForeignKey(limit_choices_to={'role': 'store_officer'}, on_delete=django.db.models.deletion.PROTECT, related_name='sm_collections_recorded', to='accounts.user')),
            ],
            options={
                'db_table': 'sales_sm_collection',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesDistributionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('material_type', models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], max_length=10)),
                ('qty_given', models.PositiveIntegerField(help_text='Number of 10kg sacks given to this person')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(limit_choices_to={'role': 'sales_manager'}, on_delete=django.db.models.deletion.PROTECT, related_name='distributions_recorded', to='accounts.user')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='sales.salesperson')),
                ('collection', models.ForeignKey(help_text='The SM collection batch these sacks came from', on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='sales.salesmanagercollection')),
            ],
            options={
                'db_table': 'sales_distribution_record',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesManagerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_transfer', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_gm', 'Pending GM Confirmation'), ('confirmed', 'Confirmed by GM'), ('rejected', 'Rejected by GM')], default='pending_gm', max_length=15)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('gm_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('confirmed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sm_payments_confirmed', to='accounts.user')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sm_payments_recorded', to='accounts.user')),
                ('sales_manager', models.ForeignKey(limit_choices_to={'role': 'sales_manager'}, on_delete=django.db.models.deletion.PROTECT, related_name='sm_payments', to='accounts.user')),
            ],
            options={
                'db_table': 'sales_sm_payment',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('material_type', models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], max_length=10)),
                ('qty_sold', models.PositiveIntegerField(help_text='Number of 10kg sacks sold by this person')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Price per sack from MD config (sales_manager channel)', max_digits=12)),
                ('gross_value', models.DecimalField(decimal_places=2, default=0, help_text='qty_sold × unit_price', max_digits=14)),
                ('commission_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_due_to_company', models.DecimalField(decimal_places=2, default=0, help_text='gross_value − commission_amount — reduces SM outstanding', max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('distribution', models.ForeignKey(help_text='The distribution batch these sales came from', on_delete=django.db.models.deletion.PROTECT, related_name='results', to='sales.salesdistributionrecord')),
                ('recorded_by', models.ForeignKey(limit_choices_to={'role': 'sales_manager'}, on_delete=django.db.models.deletion.PROTECT, related_name='sales_results_recorded', to='accounts.user')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_results', to='sales.salesperson')),
            ],
            options={
                'db_table': 'sales_result',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
