# Generated by Django 4.2.27 on 2026-03-02 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_salesrecord_channel_salesmanagercollection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesresult',
            name='distribution',
            field=models.ForeignKey(blank=True, help_text='The distribution batch these sales came from (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='sales.salesdistributionrecord'),
        ),
    ]
