# Generated by Django 4.2.27 on 2026-03-02 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_salesresult_optional_distribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdistributionrecord',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='The SM collection batch these sacks came from (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='sales.salesmanagercollection'),
        ),
    ]
