# Generated by Django 6.0.2 on 2026-03-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_salesdistributionrecord_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesresult',
            name='qty_pieces_sold',
            field=models.PositiveIntegerField(default=0, help_text='Number of 1kg pieces sold by this person'),
        ),
        migrations.AddField(
            model_name='salesresult',
            name='unit_price_piece',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per 1kg piece from MD config (sales_manager channel)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesresult',
            name='gross_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='(qty_sold × unit_price) + (qty_pieces_sold × unit_price_piece)', max_digits=14),
        ),
    ]
