# Generated by Django 6.0.2 on 2026-03-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_salesresult_qty_pieces_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesresult',
            name='amount_returned',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual money handed over by the SalesPerson to the SM', max_digits=14),
        ),
        migrations.AddField(
            model_name='salesresult',
            name='qty_pieces_returned',
            field=models.PositiveIntegerField(default=0, help_text='Number of 1kg pieces returned to SM'),
        ),
        migrations.AddField(
            model_name='salesresult',
            name='qty_returned',
            field=models.PositiveIntegerField(default=0, help_text='Number of 10kg sacks returned to SM'),
        ),
    ]
