# Generated by Django 6.0.2 on 2026-03-09 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_plain_password'),
        ('sales', '0016_salesresult_amount_returned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectSalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('material_type', models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat')], max_length=10)),
                ('product_size', models.CharField(choices=[('10kg', '10 KG Sacks')], default='10kg', max_length=5)),
                ('qty_sold', models.PositiveIntegerField(help_text='Number of sacks sold')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per sack', max_digits=12)),
                ('total_sale_value', models.DecimalField(decimal_places=2, help_text='Total sale value (auto: qty × unit_price)', max_digits=14)),
                ('amount_received_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_received_transfer', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('buyer_name', models.CharField(blank=True, help_text='Name of the customer', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_md', 'Pending MD Confirmation'), ('confirmed', 'Confirmed by MD'), ('rejected', 'Rejected by MD')], default='pending_md', max_length=15)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('md_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('confirmed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'md'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_sales_confirmed', to='accounts.user')),
                ('recorded_by', models.ForeignKey(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.PROTECT, related_name='direct_sales_recorded', to='accounts.user')),
            ],
            options={
                'db_table': 'sales_direct_payment',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
