# Generated by Django 6.0.2 on 2026-03-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_directsalepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdistributionrecord',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesdistributionrecord',
            name='commission_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salesdistributionrecord',
            name='expected_return',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesdistributionrecord',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
