# Generated by Django 6.0.2 on 2026-04-07 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_plain_password'),
        ('sales', '0018_salesdistributionrecord_commission_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_transfer', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_md', 'Pending MD Confirmation'), ('confirmed', 'Confirmed by MD'), ('rejected', 'Rejected by MD')], default='pending_md', max_length=15)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('md_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('confirmed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'md'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gm_remittances_confirmed', to='accounts.user')),
                ('recorded_by', models.ForeignKey(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.PROTECT, related_name='gm_remittances_recorded', to='accounts.user')),
            ],
            options={
                'db_table': 'sales_gm_remittance',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
