# Generated by Django 6.0.2 on 2026-04-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_gmremittance'),
    ]

    operations = [
        migrations.AddField(
            model_name='directsalepayment',
            name='labour_unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Labour price per sack at time of sale', max_digits=10),
        ),
        migrations.AddField(
            model_name='directsalepayment',
            name='total_labour_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesresult',
            name='labour_unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Labour price per sack at time of sale', max_digits=10),
        ),
        migrations.AddField(
            model_name='salesresult',
            name='total_labour_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
