# Generated by Django 6.0.2 on 2026-04-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_populate_labour_costs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directsalepayment',
            name='labour_unit_cost',
        ),
        migrations.RemoveField(
            model_name='directsalepayment',
            name='total_labour_cost',
        ),
        migrations.RemoveField(
            model_name='salesresult',
            name='amount_returned',
        ),
        migrations.RemoveField(
            model_name='salesresult',
            name='labour_unit_cost',
        ),
        migrations.RemoveField(
            model_name='salesresult',
            name='total_labour_cost',
        ),
    ]
