# Generated by Django 6.0.2 on 2026-04-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_remove_directsalepayment_labour_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesresult',
            name='amount_returned',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual money handed over by the SalesPerson to the SM', max_digits=14),
        ),
    ]
